version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - npm ci
      - npm run build
artifacts:
  files:
    - 'dist/**/*'
    - 'package.json'
    - 'package-lock.json'
